name: deploy
on:
  push:
    branches:
      - dev
      - master
      - automatic-deploys
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn --prefer-offline

      - name: Build CLI and rule definitions
        run: yarn build

  deploy-staging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/automatic-deploys'
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Deploy
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
        run: yarn rules deploy
